security:
    password_hashers:
        App\Entity\Pharmacie:
            algorithm: auto
        App\Entity\UserOrdrePharma: # Entité pour l'ordre des pharmaciens
            algorithm: auto

    providers:
        pharmacie_provider:
            entity:
                class: App\Entity\Pharmacie
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

       
                
        main:
            provider: pharmacie_provider # Définit explicitement le provider pour ce firewall
            form_login:
                login_path: login
                check_path: login
                default_target_path: pharmacie_dashboard
            logout:
                path: app_logout
                target: login
                invalidate_session: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                httponly: true

        

       

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admine, roles: ROLE_PHARMACIEN }
