# config/services.yaml
parameters:
    medicaments_directory: '%kernel.project_dir%/public/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\Service\GeocodingService:
        class: App\Service\GeocodingService

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
